# Generated by Django 5.2 on 2025-05-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_number', models.PositiveIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('location_text', models.CharField(max_length=250)),
                ('debt', models.BigIntegerField(default=0)),
                ('cooler', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('card', 'card'), ('cash', 'cash'), ('account_number', 'account_number')], max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('client_type', models.CharField(choices=[('physical_person', 'physical_person'), ('legal_person', 'legal_person')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('number_of_trips', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('the_rest', models.PositiveIntegerField(blank=True, null=True)),
                ('received', models.PositiveIntegerField(blank=True, null=True)),
                ('paid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('indebtedness', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='new', max_length=15)),
                ('payment_type', models.CharField(choices=[('card', 'card'), ('cash', 'cash'), ('account_number', 'account_number')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='common.region'),
        ),
    ]
