# Generated by Django 5.2 on 2025-04-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_number', models.PositiveIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('location_text', models.CharField(max_length=250)),
                ('debt', models.PositiveIntegerField(default=0)),
                ('cooler', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('given', models.PositiveIntegerField()),
                ('the_rest', models.PositiveIntegerField()),
                ('received', models.PositiveIntegerField()),
                ('paid', models.PositiveBigIntegerField()),
                ('indebtedness', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('yangi', 'yangi'), ('berilgan', 'berilgan')], default='yangi', max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='common.region'),
        ),
    ]
