# Generated by Django 5.2 on 2025-05-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='number_of_trips',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
