# Generated by Django 5.2 on 2025-05-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='number_of_trips',
        ),
        migrations.CreateModel(
            name='NumberOfTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_of_trips', to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
