# Generated by Django 5.2 on 2025-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_region_number_of_trips_numberoftrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('taken', 'taken')], default='new', max_length=15),
        ),
    ]
