# Generated by Django 5.2 on 2025-05-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_region_number_of_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payment_type',
        ),
    ]
