# Generated by Django 5.2 on 2025-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_order_given_alter_order_indebtedness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='given',
        ),
        migrations.AlterField(
            model_name='order',
            name='indebtedness',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='the_rest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
